In [2]:
%matplotlib inline

In [12]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [13]:
data = randn(2, 3)
data

array([[-1.8581,  1.4595,  1.0417],
       [ 0.3874, -0.0305, -0.2105]])

In [14]:
data + data

array([[-3.7161,  2.919 ,  2.0835],
       [ 0.7749, -0.0611, -0.421 ]])

In [15]:
data * 10

array([[-18.5806,  14.5948,  10.4174],
       [  3.8745,  -0.3055,  -2.1052]])

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

## 创建ndarray

In [20]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [58]:
arr2 = np.array([[1,2,3], [2.3, 4, 5]])
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(2, 3)
2
float64


In [60]:
np.array(3.5)

array(3.5)

In [59]:
arr2[0][2]

3.0

In [68]:
np.empty((2,3,3))

array([[[ -2.3158e+077,  -3.1111e+231,   2.2301e-314],
        [  2.2301e-314,   2.2301e-314,   2.2301e-314],
        [  2.2301e-314,   2.2301e-314,   2.2301e-314]],

       [[  2.2301e-314,   1.2048e+132,   1.0577e-153],
        [  9.4222e-096,   1.9536e-109,   1.0718e+160],
        [  4.0625e-144,   6.1758e-322,   1.2516e-308]]])

In [70]:
np.zeros((2,3,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [75]:
np.ones((3,))  == np.ones(3)

array([ True,  True,  True], dtype=bool)

In [76]:
np.ones(3).shape

(3,)

In [79]:
np.ones((3,)).shape

(3,)

In [80]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [83]:
a1 = np.asarray([1,2,3])

In [90]:
np.asanyarray(a1) is a1

True

In [88]:
np.array([1,2,3]) is np.array([1,2,3])

False

In [89]:
np.asanyarray(a1) is np.asanyarray(a1)

True

In [91]:
np.ones_like(a1)

array([1, 1, 1])

In [92]:
np.empty_like(a1)

array([1, 2, 3])

In [102]:
np.zeros_like(a1, dtype=np.float64)

array([ 0.,  0.,  0.])

In [103]:
a = np.random.rand(3, 2, 2)
np.empty_like(a, dtype=np.int64)

array([[[4603021953877588617, 4603493775154227560],
        [4590858736898514704, 4588284813081746624]],

       [[4586539564211061392, 4604104812851313197],
        [4600509064357682500, 4604340623710638548]],

       [[4607045559178833251, 4605532630314803865],
        [4602825757355336102, 4595828719352284128]]])

In [107]:
np.eye(5, dtype=np.int64)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## ndarray的数据类型