# pandas入门

## pandas的数据结构介绍

In [2]:
from __future__ import division
from numpy.random import randn
import numpy as np
import os
import matplotlib.pyplot as plt
np.random.seed(12345)
plt.rc('figure', figsize=(10, 6))
from pandas import Series, DataFrame
import pandas as pd
np.set_printoptions(precision=4)

### Series

In [3]:
obj = Series([4, 7, -5, 3])
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.name = 'data'
obj.index.name = 'index'
obj

index
0    4
1    7
2   -5
3    3
Name: data, dtype: int64

In [7]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index([u'd', u'b', u'a', u'c'], dtype='object')

In [10]:
print(type(obj2['a']))
obj2['a']

<type 'numpy.int64'>


-5

In [11]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [12]:
x = obj2[['c','a','d']]
x

c    3
a   -5
d    6
dtype: int64

In [13]:
x['c'] = 100
x

c    100
a     -5
d      6
dtype: int64

In [14]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [15]:
y = obj2[obj2>0]
y

d    6
b    7
c    3
dtype: int64

In [16]:
y['d'] = 100
y

d    100
b      7
c      3
dtype: int64

In [17]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [18]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [19]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [20]:
'b' in obj2

True

In [21]:
'f' in obj2

False

In [22]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [23]:
states = ['Califonia', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

In [24]:
obj4.isnull()

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [25]:
obj4.notnull()

Califonia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool

In [26]:
pd.isnull(obj4)

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [27]:
pd.notnull(obj4)

Califonia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool

In [28]:
obj3 + obj4

Califonia         NaN
Ohio          70000.0
Oregon        32000.0
Texas        142000.0
Utah              NaN
dtype: float64

In [29]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
Name: population, dtype: float64

In [30]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
Name: data, dtype: int64

In [31]:
obj5 = Series([1,2,'a'])
obj6 = Series([1,2,'b'])
obj5 + obj6

0     2
1     4
2    ab
dtype: object

In [32]:
obj5.dtype

dtype('O')

In [33]:
obj.dtype

dtype('int64')

In [34]:
sdata

{'Ohio': 35000, 'Oregon': 16000, 'Texas': 71000, 'Utah': 5000}

In [35]:
Series(sdata, index=['a', 'Ohio'])

a           NaN
Ohio    35000.0
dtype: float64

In [36]:
x = obj[:2]
x[0] = 5
obj

Bob      5
Steve    7
Jeff    -5
Ryan     3
Name: data, dtype: int64

In [37]:
print(obj.loc['Bob'])
print(obj.iloc[0])
obj.loc['Bob'] = 11
print(obj)
obj.iloc[0] = 20  # 不会修改
print(obj)

5
5
Bob      11
Steve     7
Jeff     -5
Ryan      3
Name: data, dtype: int64
Bob      20
Steve     7
Jeff     -5
Ryan      3
Name: data, dtype: int64


In [38]:
obj[obj.index[:2]] = 10
obj

Bob      10
Steve    10
Jeff     -5
Ryan      3
Name: data, dtype: int64

### DataFrame

In [39]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [40]:
frame.loc[0]

pop       1.5
state    Ohio
year     2000
Name: 0, dtype: object

In [41]:
frame['pop']

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
Name: pop, dtype: float64

In [42]:
frame[['pop', 'year']]   # view

pop  year
0  1.5  2000
1  1.7  2001
2  3.6  2002
3  2.4  2001
4  2.9  2002

In [43]:
frame.loc[[0,1], ['pop']] # view

pop
0  1.5
1  1.7

In [44]:
frame.iloc[[1,2],:]

pop state  year
1  1.7  Ohio  2001
2  3.6  Ohio  2002

In [45]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [46]:
x = DataFrame(frame, columns=['pop','state',3])

In [47]:
x.loc[0] = 1

In [48]:
x.loc[:, 'pop'] = 10

In [49]:
x

pop   state    3
0   10       1  1.0
1   10    Ohio  NaN
2   10    Ohio  NaN
3   10  Nevada  NaN
4   10  Nevada  NaN

In [50]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [51]:
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002]}

In [52]:
frame2 = DataFrame(data, index=['one','two', 'three', 'four', 'five'], columns=['year', 'state','pop', 'debt'])

In [53]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [54]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [55]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [56]:
frame2.index

Index([u'one', u'two', u'three', u'four', u'five'], dtype='object')

In [57]:
frame2.loc['three'] 

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [58]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [59]:
frame2.debt = np.arange(5)

In [60]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [61]:
val = Series([-1.2, 1.5, -1.7], index=['two', 'one', 'four'])
frame2.debt = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   1.5
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.7
five   2002  Nevada  2.9   NaN

In [62]:
frame2['eastern'] = frame2.state == 'Nevada'

In [63]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   1.5    False
two    2001    Ohio  1.7  -1.2    False
three  2002    Ohio  3.6   NaN    False
four   2001  Nevada  2.4  -1.7     True
five   2002  Nevada  2.9   NaN     True

In [64]:
del frame2['eastern']

In [65]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   1.5
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.7
five   2002  Nevada  2.9   NaN

In [66]:
frame2 = frame2.iloc[0:4]

In [67]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   1.5
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.7

In [68]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [69]:
DataFrame(pop, index=[2000, 2001, 2002, 2003])

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [70]:
x = frame3.T
x

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [71]:
x[2000] = 12

In [72]:
x

2000  2001  2002
Nevada    12   2.4   2.9
Ohio      12   1.7   3.6

In [73]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [74]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [75]:
print(pdata)

{'Ohio': 2000    1.5
2001    1.7
Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
2001    2.4
Name: Nevada, dtype: float64}


In [76]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [77]:
DataFrame([frame3['Ohio'], frame3['Nevada']])

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [78]:
y = frame3.loc[[2000],['Ohio']]
y[:]=100
print(y)
frame3

       Ohio
2000  100.0


Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [79]:
x = frame3.iloc[[1],[1]]
x[:] = 200
x

Ohio
2001  200.0

In [80]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [81]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [82]:
frame3.values.shape

(3, 2)

In [83]:
frame3.Ohio.values.shape

(3,)

In [84]:
frame3.iloc[0].values

array([ nan,  1.5])

In [85]:
frame3.index.name = 'niubi'

In [86]:
frame3.columns.name = 'lihai'

In [87]:
frame3

lihai  Nevada  Ohio
niubi              
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [88]:
frame2.values

array([[2000, 'Ohio', 1.5, 1.5],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.7]], dtype=object)

In [89]:
frame2.values

array([[2000, 'Ohio', 1.5, 1.5],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.7]], dtype=object)

### 索引对象

In [90]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index([u'a', u'b', u'c'], dtype='object')

In [91]:
index[1:]

Index([u'b', u'c'], dtype='object')

In [92]:
# index[1] = 'd'

In [93]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [94]:
index2 = index[:2]
obj3 = Series([1.5, -2.], index=index2)

In [95]:
obj3.index is index2

True

In [96]:
obj4 = Series([1.5, -2.], index=pd.Index(np.arange(2)))

In [97]:
obj4.index is obj3.index

False

In [98]:
obj4 + obj3

0    3.0
1   -4.0
dtype: float64

In [99]:
frame3

lihai  Nevada  Ohio
niubi              
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [100]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name=u'niubi')

In [101]:
2000 in frame3.index

True

In [102]:
frame3.columns

Index([u'Nevada', u'Ohio'], dtype='object', name=u'lihai')

In [103]:
'Nevada' in frame3.columns

True

In [104]:
print(index)
index.append(frame3.index)

Int64Index([0, 1, 2], dtype='int64')


Int64Index([0, 1, 2, 2000, 2001, 2002], dtype='int64')

In [105]:
a = index.append(frame3.columns).append(index)
a

Index([0, 1, 2, u'Nevada', u'Ohio', 0, 1, 2], dtype='object')

In [106]:
a.is_unique

False

In [108]:
a.unique().is_unique

True

In [109]:
a.unique()

Index([0, 1, 2, u'Nevada', u'Ohio'], dtype='object')

## 基本功能

### 重新索引

In [192]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [193]:
xx = obj.iloc[:2]
xx[0] = 10
print(xx)
print(obj)

d    10.0
b     7.2
dtype: float64
d    10.0
b     7.2
a    -5.3
c     3.6
dtype: float64


In [188]:
obj2 = obj.reindex(['a', 'd', 'b', 'c', 'e'])
obj2

a    -5.3
d    10.0
b     7.2
c     3.6
e     NaN
dtype: float64

In [116]:
obj3 = obj.reindex(['a', 'd', 'b', 'c', 'e'], fill_value=0)
obj3

a   -5.3
d    4.5
b    7.2
c    3.6
e    0.0
dtype: float64

In [117]:
obj4 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj4

0      blue
2    purple
4    yellow
dtype: object

In [120]:
obj5 = obj4.reindex(range(6), method='ffill')
obj5

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [121]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [132]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'], fill_value=100)
frame2

Ohio  Texas  California
a     0      1           2
b   100    100         100
c     3      4           5
d     6      7           8

In [145]:
states = ['California', 'Ohio', 'Texas', ]
frame.reindex(columns=states)

California  Ohio  Texas
a           2     0      1
c           5     3      4
d           8     6      7

In [150]:
frame.reindex(index=['a', 'b', 'c', 'd'], columns=states)

California  Ohio  Texas
a         2.0   0.0    1.0
b         NaN   NaN    NaN
c         5.0   3.0    4.0
d         8.0   6.0    7.0

In [153]:
frame.loc[['a', 'b', 'c', 'd'], states]

California  Ohio  Texas
a         2.0   0.0    1.0
b         NaN   NaN    NaN
c         5.0   3.0    4.0
d         8.0   6.0    7.0

In [158]:
frame.at['d', 'California']

8

In [159]:
frame.index

Index([u'a', u'c', u'd'], dtype='object')

In [163]:
frame.columns

Index([u'Ohio', u'Texas', u'California'], dtype='object')

In [170]:
frame.ix[[0,1], ['Texas','California']]

Texas  California
a      1           2
c      4           5

In [171]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [169]:
frame.ix[[0,1], 'Texas']  

a    1
c    4
Name: Texas, dtype: int64

### 丢弃指定轴上的项

In [195]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [202]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [203]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [212]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [208]:
data.drop(['Ohio', 'Colorado'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [209]:
data.drop('one', axis=1)

two  three  four
Ohio        1      2     3
Colorado    5      6     7
Utah        9     10    11
New York   13     14    15

In [213]:
data.drop('Ohio', inplace=True)  # 就地丢弃，小心使用
data 

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 索引、选取和过滤

In [214]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [216]:
obj['a']

0.0

In [217]:
obj[0]

0.0

In [221]:
obj[2:4]

c    2.0
d    3.0
Name: a, dtype: float64

In [219]:
obj['a':'c']

a    0.0
b    1.0
c    2.0
Name: a, dtype: float64

In [222]:
obj['b': 'c'] = 10
obj

a     0.0
b    10.0
c    10.0
d     3.0
Name: a, dtype: float64

In [225]:
x = obj[['b', 'a', 'd']]
x[:] = 100
print(x)
obj

b    100.0
a    100.0
d    100.0
Name: a, dtype: float64


a     0.0
b    10.0
c    10.0
d     3.0
Name: a, dtype: float64

In [226]:
obj[[1, 3]]

b    10.0
d     3.0
Name: a, dtype: float64

In [227]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
Name: a, dtype: float64

In [292]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [233]:
data.two = 5

In [234]:
data

one  two  three  four
Ohio        0    5      2     3
Colorado    4    5      6     7
Utah        8    5     10    11
New York   12    5     14    15

In [235]:
data.two

Ohio        5
Colorado    5
Utah        5
New York    5
Name: two, dtype: int64

In [236]:
data['two']

Ohio        5
Colorado    5
Utah        5
New York    5
Name: two, dtype: int64

In [240]:
data[['two','one']] = 11

In [241]:
data

one  two  three  four
Ohio       11   11      2     3
Colorado   11   11      6     7
Utah       11   11     10    11
New York   11   11     14    15

In [244]:
data[:2]

one  two  three  four
Ohio       11   11      2     3
Colorado   11   11      6     7

In [245]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [246]:
data[data['three'] > 5]

one  two  three  four
Colorado   11   11      6     7
Utah       11   11     10    11
New York   11   11     14    15

In [247]:
data < 5

one    two  three   four
Ohio      False  False   True   True
Colorado  False  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [249]:
data[data<5] = 0
data

one  two  three  four
Ohio       11   11      0     0
Colorado   11   11      6     7
Utah       11   11     10    11
New York   11   11     14    15

### 用loc和iloc进行选取

In [250]:
data.loc['Colorado', ['two', 'three']]

two      11
three     6
Name: Colorado, dtype: int64

In [251]:
data.loc['Colorado', 'two']

11

In [252]:
data.loc['Colorado', ['two']]

two    11
Name: Colorado, dtype: int64

In [261]:
data.loc[['Colorado'], ['two']]

two
Colorado   11

In [262]:
data.at['Colorado', 'two']

11

In [256]:
data.iloc[0,2]

0

In [257]:
data.iloc[[0],2]

Ohio    0
Name: three, dtype: int64

In [258]:
data.iloc[0,[2]]

three    0
Name: Ohio, dtype: int64

In [263]:
data.iat[0,2]

0

In [266]:
data.iloc[[1, 2], [3, 0, 1]] = 100
data

one  two  three  four
Ohio       11   11      0     0
Colorado  100  100      6   100
Utah      100  100     10   100
New York   11   11     14    15

In [267]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado   100  100  100
Utah       100  100  100

In [268]:
data.loc[:'Utah', 'two']

Ohio         11
Colorado    100
Utah        100
Name: two, dtype: int64

In [273]:
data.loc['Utah':'New York']

one  two  three  four
Utah      100  100     10   100
New York   11   11     14    15

In [274]:
data['Utah':'New York']

one  two  three  four
Utah      100  100     10   100
New York   11   11     14    15

In [281]:
data.iloc[0:2]

one  two  three  four
Ohio       11   11      0     0
Colorado  100  100      6   100

In [293]:
data > 5

one    two  three   four
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [294]:
data.iloc[:, :3]

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [296]:
data[data<5] = 100

In [297]:
data

one  two  three  four
Ohio      100  100    100   100
Colorado  100    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [302]:
data.ix[['Colorado', 'Utah'], [0,3,2]]

one  four  three
Colorado  100     7      6
Utah        8    11     10

In [307]:
data.iloc[[2], :]

one  two  three  four
Utah    8    9     10    11

In [315]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data.ix[data.three>5, :3]

/Users/thomas_young/miniconda3/envs/bunnies/lib/python2.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.


one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [317]:
data.iloc[:, :3][data.three > 5]  # 这是更好的方法

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

### 整数索引

In [332]:
# 为了避免歧义，不要使用data[1]这样的用法，尽量使用iloc和loc
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [328]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [329]:
ser.iloc[:1]

0    0.0
dtype: float64

### 算术运算和数据对齐

In [333]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [334]:
print(s1)
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [335]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [340]:
s1.add(s2, fill_value=10)

a     5.2
c     1.1
d    13.4
e     0.0
f    14.0
g    13.1
dtype: float64

In [341]:
s2.add(s1, fill_value=10)

a     5.2
c     1.1
d    13.4
e     0.0
f    14.0
g    13.1
dtype: float64

In [343]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [344]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [345]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [346]:
df1.add(df2, fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [348]:
df2.add(df1, fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [354]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [355]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [356]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [357]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [358]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [359]:
1 / df2

a         b         c         d         e
0       inf  1.000000  0.500000  0.333333  0.250000
1  0.200000       NaN  0.142857  0.125000  0.111111
2  0.100000  0.090909  0.083333  0.076923  0.071429
3  0.066667  0.062500  0.058824  0.055556  0.052632

In [362]:
df2.rdiv(1, fill_value=100)

a         b         c         d         e
0       inf  1.000000  0.500000  0.333333  0.250000
1  0.200000  0.010000  0.142857  0.125000  0.111111
2  0.100000  0.090909  0.083333  0.076923  0.071429
3  0.066667  0.062500  0.058824  0.055556  0.052632

In [367]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### DataFrame和Series之间的运算

In [371]:
arr = np.arange(12.).reshape((3, 4))
print(arr)
arr - arr[0]

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]


array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [376]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                         columns=list('bde'),
                        index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame)
series = frame.iloc[0]
frame - series

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [379]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame.add(series2)

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [382]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [393]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 函数应用与映射