In [2]:
%matplotlib inline

In [3]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [13]:
data = randn(2, 3)
data

array([[-1.8581,  1.4595,  1.0417],
       [ 0.3874, -0.0305, -0.2105]])

In [14]:
data + data

array([[-3.7161,  2.919 ,  2.0835],
       [ 0.7749, -0.0611, -0.421 ]])

In [15]:
data * 10

array([[-18.5806,  14.5948,  10.4174],
       [  3.8745,  -0.3055,  -2.1052]])

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

## 创建ndarray

In [20]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [58]:
arr2 = np.array([[1,2,3], [2.3, 4, 5]])
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(2, 3)
2
float64


In [60]:
np.array(3.5)

array(3.5)

In [59]:
arr2[0][2]

3.0

In [68]:
np.empty((2,3,3))

array([[[ -2.3158e+077,  -3.1111e+231,   2.2301e-314],
        [  2.2301e-314,   2.2301e-314,   2.2301e-314],
        [  2.2301e-314,   2.2301e-314,   2.2301e-314]],

       [[  2.2301e-314,   1.2048e+132,   1.0577e-153],
        [  9.4222e-096,   1.9536e-109,   1.0718e+160],
        [  4.0625e-144,   6.1758e-322,   1.2516e-308]]])

In [70]:
np.zeros((2,3,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [75]:
np.ones((3,))  == np.ones(3)

array([ True,  True,  True], dtype=bool)

In [76]:
np.ones(3).shape

(3,)

In [79]:
np.ones((3,)).shape

(3,)

In [80]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
a1 = np.asarray([1,2,3])

In [9]:
np.asarray(a1) is a1

True

In [10]:
np.array([1,2,3]) is np.array([1,2,3])

False

In [12]:
np.asarray(a1) is np.asarray(a1)

True

In [14]:
np.asanyarray(a1)

array([1, 2, 3])

In [91]:
np.ones_like(a1)

array([1, 1, 1])

In [92]:
np.empty_like(a1)

array([1, 2, 3])

In [102]:
np.zeros_like(a1, dtype=np.float64)

array([ 0.,  0.,  0.])

In [103]:
a = np.random.rand(3, 2, 2)
np.empty_like(a, dtype=np.int64)

array([[[4603021953877588617, 4603493775154227560],
        [4590858736898514704, 4588284813081746624]],

       [[4586539564211061392, 4604104812851313197],
        [4600509064357682500, 4604340623710638548]],

       [[4607045559178833251, 4605532630314803865],
        [4602825757355336102, 4595828719352284128]]])

In [107]:
np.eye(5, dtype=np.int64)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## ndarray的数据类型

In [4]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [5]:
arr2 = np.array([1, 2, 3], dtype=np.int)
arr2.dtype

dtype('int64')

In [6]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [16]:
arr = arr.astype('f8')
arr.dtype

dtype('float64')

In [19]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr.dtype)
arr.astype(np.int32)

float64


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [21]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float32)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.], dtype=float32)

In [33]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([3125313536,      32661, 3125313536,      32661,  323918376,
                1,  292522704,     131073], dtype=uint32)

In [90]:
numeric_strings = np.array(['1.2', '-9.6', '42'], dtype=np.string_)
numeric_strings

array(['1.2', '-9.6', '42'],
      dtype='|S4')

In [91]:
numeric_strings.astype(np.float)

array([  1.2,  -9.6,  42. ])

In [92]:
invalid_numeric_strings = np.array(['x2', '-92', '42'])
invalid_numeric_strings

array(['x2', '-92', '42'],
      dtype='|S3')

In [93]:
try:
    invalid_numeric_strings.astype(int)
except ValueError as e:
    print(e)

invalid literal for int() with base 10: 'x2'


In [85]:
invalid_numeric_obj = np.array(['x2', '-92', object()])
invalid_numeric_obj

array(['x2', '-92', <object object at 0x11160a570>], dtype=object)

## 数组与标量之间的运算

In [61]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [62]:
arr * arr


array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [63]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [64]:
1 / arr

array([[ 1.    ,  0.5   ,  0.3333],
       [ 0.25  ,  0.2   ,  0.1667]])

## 基本的索引和切片

In [100]:
arr = np.arange(10)
print(arr.dtype)
arr

int64


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
arr[5] = 100.88

In [103]:
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [105]:
arr[8:10] = 12
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,  12,  12])

In [108]:
arr_slice = arr[1:3]
arr_slice

array([1, 2])

In [109]:
arr_slice[:] = -100
arr

array([   0, -100, -100,    3,    4,  100,    6,    7,   12,   12])

In [113]:
l = [1, 2, 3, 4]
l_slice = l[1:3]
print(l_slice)
l_slice[1] = 13
print(l_slice)
print(l)

[2, 3]
[2, 13]
[1, 2, 3, 4]


In [116]:
arr = np.arange(10)
arr_slice_copy = arr[1:3].copy()
arr_slice_copy[:] = 100
arr_slice_copy

array([100, 100])

In [117]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
arr2d = np.array([np.arange(i+1, i+4) for i in range(3)], dtype=np.float32)
print([np.arange(i+1, i+4) for i in range(3)])
arr2d

[array([1, 2, 3]), array([2, 3, 4]), array([3, 4, 5])]


array([[ 1.,  2.,  3.],
       [ 2.,  3.,  4.],
       [ 3.,  4.,  5.]], dtype=float32)

In [150]:
arr2d[0][2] + 10

13.0

In [151]:
arr2d[0, 2]

3.0

In [152]:
arr3d_ = np.array([arr2d, arr2d])
arr3d_

array([[[ 1.,  2.,  3.],
        [ 2.,  3.,  4.],
        [ 3.,  4.,  5.]],

       [[ 1.,  2.,  3.],
        [ 2.,  3.,  4.],
        [ 3.,  4.,  5.]]], dtype=float32)

In [153]:
arr2d[0, 2] = -1000
arr2d

array([[    1.,     2., -1000.],
       [    2.,     3.,     4.],
       [    3.,     4.,     5.]], dtype=float32)

In [154]:
arr3d_

array([[[ 1.,  2.,  3.],
        [ 2.,  3.,  4.],
        [ 3.,  4.,  5.]],

       [[ 1.,  2.,  3.],
        [ 2.,  3.,  4.],
        [ 3.,  4.,  5.]]], dtype=float32)

In [157]:
arr2d = np.array([np.arange(i+1, i+4) for i in range(3)], dtype=np.float32)
arr3d = np.array([arr2d.copy(), arr2d.copy()])
arr3d

array([[[ 1.,  2.,  3.],
        [ 2.,  3.,  4.],
        [ 3.,  4.,  5.]],

       [[ 1.,  2.,  3.],
        [ 2.,  3.,  4.],
        [ 3.,  4.,  5.]]], dtype=float32)

In [158]:
arr2d[0, 2] = -1000
arr2d

array([[    1.,     2., -1000.],
       [    2.,     3.,     4.],
       [    3.,     4.,     5.]], dtype=float32)

In [159]:
arr3d

array([[[ 1.,  2.,  3.],
        [ 2.,  3.,  4.],
        [ 3.,  4.,  5.]],

       [[ 1.,  2.,  3.],
        [ 2.,  3.,  4.],
        [ 3.,  4.,  5.]]], dtype=float32)

In [169]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [170]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
old_values = arr3d[0]
arr3d[0, 1, 1:] = 42

In [172]:
arr3d

array([[[ 1,  2,  3],
        [ 4, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [174]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [175]:
arr3d[1, 0]

array([7, 8, 9])

## 切片索引

In [178]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [177]:
arr2d

array([[    1.,     2., -1000.],
       [    2.,     3.,     4.],
       [    3.,     4.,     5.]], dtype=float32)

In [179]:
arr2d[:2]

array([[    1.,     2., -1000.],
       [    2.,     3.,     4.]], dtype=float32)

In [181]:
arr2d[:2, 1:] = 4

In [182]:
arr2d

array([[ 1.,  4.,  4.],
       [ 2.,  4.,  4.],
       [ 3.,  4.,  5.]], dtype=float32)

In [189]:
b1 = arr2d[0:1, :]
print(b1.shape)
b1

(1, 3)


array([[ 1.,  4.,  4.]], dtype=float32)

In [188]:
b2 = arr2d[0, :]
print(b2.shape)
b2

(3,)


array([ 1.,  4.,  4.], dtype=float32)

In [192]:
b3 = arr2d[2, :1]
print(b3.shape)
b3

(1,)


array([ 3.], dtype=float32)

In [195]:
arr2d[:, :1]

array([[ 1.],
       [ 2.],
       [ 3.]], dtype=float32)

In [196]:
arr2d[:2, 1:] = 0
arr2d

array([[ 1.,  0.,  0.],
       [ 2.,  0.,  0.],
       [ 3.,  4.,  5.]], dtype=float32)